[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
json-target-spec = true
[build]
target = "x86_64-rustix.json"
[target.'cfg(target_os = "none")']
rustflags = [
    "-C", "link-arg=boot/o/multiboot.o",
    "-C", "link-arg=boot/o/entry.o",
    "-C", "link-arg=-Tlinker.ld"
]

#runner = "bootimage runner"
